import math
n=50
print(int(math.log(math.log(n, 2))))
print(int(math.sqrt(math.log(n, 4))))
print(int(math.log(n, 3)))
print(int(math.log(n, 2) ** 2))
print(int(math.sqrt(n)))
print(int(n / math.log(n, 5)))
print(int(math.log(math.factorial(n),2)))
print(int(3 ** math.log(n, 2)))
print(int(n ** 2))
print(int(7 ** (math.log(n, 2))))
print(int(math.log(n, 2) ** (math.log(n, 2))))
print(int(n ** (math.sqrt(n))))
print(int(n ** (math.log(n, 2))))
print(int(2 ** n))
print(int(4 ** n))
print(int(2 ** (3 * n)))
print(int(math.factorial(n)))
#print(2 ** (2 ** n))
